Разложить матрицу в SVD.
Цель: Для матрицы A=[[3 7],[5 2]] выполнить сингулярное разложение в python с использованием библиотеки numpy (функция linalg.svd). Записать получившуюся матрицу преобразования. 

In [1]:
import numpy as np

In [2]:
matrix_A = np.array([[3, 7],
                     [5, 2]])

In [3]:
u, s, vh = np.linalg.svd(matrix_A, full_matrices=True)

In [4]:
u

array([[-0.85065081, -0.52573111],
       [-0.52573111,  0.85065081]])

In [5]:
s

array([8.71337969, 3.32821489])

In [6]:
np.diag(s)

array([[8.71337969, 0.        ],
       [0.        , 3.32821489]])

In [7]:
vh

array([[-0.59455781, -0.80405286],
       [ 0.80405286, -0.59455781]])

In [8]:
# Ответ:
np.dot(u, np.diag(s))

array([[3., 7.],
       [5., 2.]])